theme: minima
title: Huichen Sun's Page
author: Huichen Sun (Veronica)
email: hus870@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
 This is my personal page

# social links
twitter_username: your-twitter-handle
github_username:  vero1126nica

show_excerpts: true # set to false to remove excerpts on the homepage
